In [38]:
import numpy as np       #  导入numpy库
from scipy.io import loadmat    # 导入读取mat文件的模块
from sklearn import model_selection     #  模型比较和选择包
from sklearn.metrics import confusion_matrix     # 计算混淆矩阵，主要用来评估分类的准确性
from sklearn.metrics import accuracy_score     #  计算精度得分
import warnings
warnings.filterwarnings("ignore")     # 忽略所有警告
data = loadmat('D:/AAA_poetrycoder/course_exercises/jupyter_projects/Machine_Learning/10_digital_手写数字识别')
data

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011',
 '__version__': '1.0',
 '__globals__': [],
 'X': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 'y': array([[10],
        [10],
        [10],
        ...,
        [ 9],
        [ 9],
        [ 9]], dtype=uint8)}

In [39]:
# 把X,y转化为数组形式，以便于计算
X=data['X']     # 提取X变量
y=data['y']     # 提取y变量
X.shape,y.shape    # X,y的形状
X[0,100:120]    #  矩阵x第一行第101列至第119列的数据

array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  1.28335523e-17, -3.26286765e-04, -1.38651604e-02,
        8.15651552e-02,  3.82800381e-01,  8.57849775e-01,  1.00109761e+00,
        9.69710638e-01,  9.30928598e-01,  1.00383757e+00,  9.64157356e-01,
        4.49256553e-01, -5.60408259e-03, -3.78319036e-03,  0.00000000e+00])

In [40]:
from sklearn.neural_network import MLPClassifier    # 导入MLP分类器程序库
from sklearn.preprocessing import StandardScaler   # 导入标准化库
scaler = StandardScaler()     # 标准化转换
scaler.fit(X)      #  训练标准化对象
X=scaler.transform(X)    # 转换数据集

In [41]:
# 将数据计划分为训练集与测试集
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25, random_state=2)  # 以25%的数据构建测试样本，剩余作为训练样本
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((3750, 400), (1250, 400), (3750, 1), (1250, 1))

In [42]:
# 设置MLP算法，设置参数，设置一个隐藏层，50个神经元
mlp=MLPClassifier(solver='adam',activation='tanh', alpha=1e-5,
                hidden_layer_sizes=(50,),learning_rate_init=0.001,max_iter=2000)
mlp.fit(X_train,y_train)   # 对训练集进行学习

MLPClassifier(activation='tanh', alpha=1e-05, hidden_layer_sizes=(50,),
              max_iter=2000)

In [43]:
# 展示训练结果，并对测试集进行预测
print("每层网络层系数矩阵维度：\n", [coef.shape for coef in mlp.coefs_])
y_pred=mlp.predict(X_test)    # 预测测试集输出
print("预测结果：\n", y_pred)
print(mlp.intercepts_)    # 列表中第i个元素代表i+1层的偏差向量

每层网络层系数矩阵维度：
 [(400, 50), (50, 10)]
预测结果：
 [7 8 3 ... 3 7 9]
[array([-0.09667222, -0.11795363, -0.08865131,  0.02043982, -0.04519954,
        0.22297979, -0.16650224,  0.10189387, -0.25032992,  0.12002862,
        0.00800096, -0.24649704,  0.01414557, -0.2013584 ,  0.09473179,
       -0.10070734, -0.08448285,  0.17993468, -0.15861929,  0.18284301,
        0.2149319 , -0.1231854 ,  0.10302452, -0.06163986,  0.09678875,
        0.02981135, -0.02975612,  0.05092258, -0.15590353,  0.10559905,
        0.01640999,  0.22023882,  0.12081446,  0.15364154,  0.14706512,
        0.13427347,  0.05302242, -0.08047777, -0.20032273,  0.10831868,
       -0.28713184,  0.02474104,  0.01152336,  0.00980718, -0.19047035,
       -0.16686207, -0.07065452, -0.04718417,  0.12046368,  0.31159728]), array([-0.04461358,  0.27310002, -0.22653179,  0.01799056,  0.35356883,
       -0.36246355, -0.01597903,  0.27141187,  0.30545354, -0.22938767])]


In [44]:
print(accuracy_score(y_test,y_pred))     # 计算准确率
confusion_matrix(y_true=y_test,y_pred=y_pred)     # 计算混淆矩阵

0.916


array([[118,   1,   2,   0,   0,   0,   2,   2,   1,   0],
       [  1, 105,   1,   1,   0,   5,   2,   3,   1,   0],
       [  1,   1, 110,   1,   7,   1,   2,   1,   1,   0],
       [  2,   1,   0, 127,   0,   1,   0,   0,   4,   0],
       [  0,   2,   3,   0, 102,   5,   0,   2,   0,   0],
       [  1,   4,   0,   0,   2, 111,   0,   0,   0,   0],
       [  1,   1,   0,   1,   0,   0, 114,   1,   4,   1],
       [  3,   0,   2,   1,   3,   1,   1, 125,   2,   3],
       [  0,   0,   2,   3,   1,   1,   3,   1, 105,   1],
       [  0,   0,   0,   1,   3,   0,   0,   0,   0, 128]], dtype=int64)