In [3]:
import numpy as np

data = [988, 1005, 1002, 1012, 981, 999, 1004, 975, 979, 1001]
print("原数据:\n", data)
print("原数据的次序统计量为:\n", np.sort(data))
print("极小观测值:\n", np.min(data))
print("极大观测值:\n", np.max(data))
print("极小值位置:\n", np.argmin(data)+1,
     "\n极大值位置:\n", np.argmax(data)+1)

原数据:
 [988, 1005, 1002, 1012, 981, 999, 1004, 975, 979, 1001]
原数据的次序统计量为:
 [ 975  979  981  988  999 1001 1002 1004 1005 1012]
极小观测值:
 975
极大观测值:
 1012
极小值位置:
 8 
极大值位置:
 4


In [1]:
import numpy as np
import math
x = [15.3, 13.0, 16.7, 14.2, 14.5, 14.5, 15.9, 15.0, 15.1, 16.4,
    16.0, 13.9, 15.1, 15.3, 14.5, 13.3, 13.6, 15.9, 14.5, 15.1]
x.append(15.2)
print('数据:\n', x)
print('数据的五分位数:\n', np.percentile(x, [0, 25, 50, 75, 100]))   # percentile函数的对象必须是列表！列表里的数是百分制的！
print('数据的极差:\n', max(x)-min(x))

数据:
 [15.3, 13.0, 16.7, 14.2, 14.5, 14.5, 15.9, 15.0, 15.1, 16.4, 16.0, 13.9, 15.1, 15.3, 14.5, 13.3, 13.6, 15.9, 14.5, 15.1, 15.2]
数据的五分位数:
 [13.  14.5 15.1 15.3 16.7]
数据的极差:
 3.6999999999999993


In [3]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.array([15.3, 13.0, 16.7, 14.2, 14.5, 14.5, 15.9, 15.0, 15.1, 16.4,
    16.0, 13.9, 15.1, 15.3, 14.5, 13.3, 13.6, 15.9, 14.5, 15.1]),columns = ['数据框数据'])
print(df.quantile([0, 0.25, 0.5, 0.75, 1]))    #  quantile函数的对象里的数必须是小数

       数据框数据
0.00  13.000
0.25  14.425
0.50  15.050
0.75  15.450
1.00  16.700


In [17]:
# 自己的改进程序
# 自编函数集成功能

import numpy as np
import pandas as pd

Shuju = [15.3, 13.0, 16.7, 14.2, 14.5, 14.5, 15.9, 15.0, 15.1, 16.4,
         16.0, 13.9, 15.1, 15.3, 14.5, 13.3, 13.6, 15.9, 14.5, 15.1]

shuju = pd.Series(Shuju)  # 列表转换为序列

def fenweishu(x):
    shuzhi = [x.count(), x.min(), x.quantile(.25), x.median(), x.quantile(.75), x.max()]
    tongjiliang = ['计数', '最小值', '下四分位数', '中位数', '上四分位数','最大值']
    fuhao = ['Count', 'Min', 'Q1(25%)', 'Median', 'Q3(75%)', 'Max']
    shujukuang = pd.DataFrame({'统计量':tongjiliang, '符号':fuhao, '数值':shuzhi})
    return(shujukuang)
fenweishu(shuju)

统计量       符号      数值
0     计数    Count  20.000
1    最小值      Min  13.000
2  下四分位数  Q1(25%)  14.425
3    中位数   Median  15.050
4  上四分位数  Q3(75%)  15.450
5    最大值      Max  16.700

In [18]:
import scipy.stats as ss  #  用于统计分析和概率分布计算的重要库
# 能进行概率分布计算、统计假设检验、描述性统计与数据探索、线性回归与相关性分析、统计模型与分布拟合等等统计分析和概率计算

import numpy as np
x = np.array([2.5, 2.39, 2.40, 2.51, 2.48, 2.52, 2.54, 2.53])
print('原数据:\n', x)
print('秩统计量:\n', ss.rankdata(x))    #  求秩
print('升序数据的原下标:\n', x.argsort()+1)   #  以原数据的顺序返回秩，方便多个列表混合求秩再切片

原数据:
 [2.5  2.39 2.4  2.51 2.48 2.52 2.54 2.53]
秩统计量:
 [4. 1. 2. 5. 3. 6. 8. 7.]
升序数据的原下标:
 [2 3 5 1 4 6 8 7]


In [20]:
import scipy.stats as ss 
import numpy as np
x = np.array([1.51, 1.80, 1.35, 1.16, 1.72, 1.68, 1.62, 1.45, 1.43, 1.79])
print('原数据:\n', x)
print('秩统计量:\n', ss.rankdata(x))   
print('升序数据的原下标:\n', x.argsort()+1)  

原数据:
 [1.51 1.8  1.35 1.16 1.72 1.68 1.62 1.45 1.43 1.79]
秩统计量:
 [ 5. 10.  2.  1.  8.  7.  6.  4.  3.  9.]
升序数据的原下标:
 [ 4  3  9  8  1  7  6  5 10  2]


In [21]:
import scipy.stats as ss
x = [2.45, 2.20, 2.80, 2.20, 2.34, 2.45, 2.25, 2.65, 2.20]   # 有重复的数据
y = list(ss.rankdata(x))
print("原数据的秩:\n", y)
z = x.index(2.20)         # 数据2.20的位置索引
print("数据2.20的秩:", y[z])
print("数据2.20的结长:",y.count(y[z]) )   # 某数据的结长：与该数据数值相等的数据的个数

原数据的秩:
 [6.5, 2.0, 9.0, 2.0, 5.0, 6.5, 4.0, 8.0, 2.0]
数据2.20的秩: 2.0
数据2.20的结长: 3


In [2]:
import scipy.stats as ss
x = [-0.2, 0.28, -0.1, -0.15, 0.01, 0.12, 0.13, 0.11, -0.05, 0.16]
print('原数据：\n', x)
y = [abs(i) for i in x]      ## 列表解析式生成绝对值数据
z = ss.rankdata(y)           ## 绝对值数据的秩
for i in range(len(x)):      ## 在序列x中循环
    if x[i] <= 0:            ## 原数据<=0
        z[i] = 0             ## 对应的绝对值秩改为0
    else:                    ## 原数据>0
        pass                 ## 跳过
print("符号统计量：\n", z)

原数据：
 [-0.2, 0.28, -0.1, -0.15, 0.01, 0.12, 0.13, 0.11, -0.05, 0.16]
符号统计量：
 [ 0. 10.  0.  0.  1.  5.  6.  4.  0.  8.]


In [20]:
from scipy.stats import rankdata

x = [0.04, 0.04, 0.32, -0.36, 0.08, 0.82, -0.23, 0.18, 0.43, 0.48,
     0.58, 0.28, 0.47, 0.22, 0.56, 0.44, -0.11, -0.28, 0.33, 0.09]

y = [abs(i) for i in x]      ## 绝对值
print('数据绝对值：\n', y)

y_rank = rankdata(y)      ## 求秩
for i in range(len(x)):
    if x[i] <= 0:
        y_rank[i] = 0
    else:
        pass
jrs = sum(y_rank)

print('符号秩：\n', y_rank)
print('绝对秩和：', jrs)

数据绝对值：
 [0.04, 0.04, 0.32, 0.36, 0.08, 0.82, 0.23, 0.18, 0.43, 0.48, 0.58, 0.28, 0.47, 0.22, 0.56, 0.44, 0.11, 0.28, 0.33, 0.09]
符号秩：
 [ 1.5  1.5 11.   0.   3.  20.   0.   6.  14.  17.  19.   9.5 16.   7.
 18.  15.   0.   0.  12.   4. ]
绝对秩和： 174.5


In [21]:
## 判断是否有结
from numpy import *
from collections import Counter  
## collections库提供了更灵活高效的数据结构，包含多种实用容器类
## Counter函数相当于计数器，统计可哈希对象的出现次数，返回字典形式结果

x = [0.04, 0.04, 0.32, -0.36, 0.08, 0.82, -0.23, 0.18, 0.43, 0.48,
     0.58, 0.28, 0.47, 0.22, 0.56, 0.44, -0.11, -0.28, 0.33, 0.09]

counter = Counter(x)

tau = [count[1] for count in counter.items() if count[1] > 1]
print('结长列表：', tau)

fac = sum([(i**3 - i) for i in tau])
print('修正因子：',round(fac, 4))


结长列表： [2]
修正因子： 6


In [22]:
counter

Counter({0.04: 2,
         0.32: 1,
         -0.36: 1,
         0.08: 1,
         0.82: 1,
         -0.23: 1,
         0.18: 1,
         0.43: 1,
         0.48: 1,
         0.58: 1,
         0.28: 1,
         0.47: 1,
         0.22: 1,
         0.56: 1,
         0.44: 1,
         -0.11: 1,
         -0.28: 1,
         0.33: 1,
         0.09: 1})

In [24]:
from scipy.stats import norm

def r(n, alpha = 0.05):
    a = abs(jrs - n * (n + 1) / 4)
    b = sqrt(n*(n+1)*(2*n+1)/24 - fac/48)
    u = norm.ppf(1-alpha/2, loc = 0, scale = 1)
    if a > b * u:
        print('拒绝原假设,认为F(x)的对称中心不等于0。')
    else:
        print('接受原假设,认为F(x)的对称中心等于0。')
r(len(x))

拒绝原假设,认为F(x)的对称中心不等于0。
